/** Product / material matrix from bazaar-products-export-2026-06-20.json */

export const PRODUCTS = [
  "Pouches Combo",
  "Jar Combo",
  "Tube Combo",
  "Labels (Roll)",
  "Labels (Sheet)",
  "Folding Cartons / Boxes",
  "Business Cards",
  "Flyers / Postcards",
  "Booklets",
  "Diecut Stickers",
  "Vinyl Labels / 54'' Rolls",
  "Vinyl Signage",
  "Banners / Large Format",
  "Window Decals",
  "Wallpaper",
  "Sheet Products (Boyd)",
  "Apparel",
  "Pouches Only",
  "Tube Only",
  "Jar Only",
  "Other",
] as const;

export const MATERIALS = [
  // Pouches / Cosmetic Web
  "Pouch Double sided",
  "Pouche One sided",
  "Clear Cosmetic Web",
  "White Cosmetic Web",
  "Silver Cosmetic Web",
  // Jar / Tube combos
  "Plastic & Side & Top",
  "Plastic & Side",
  "Plastic & Top",
  "Plastic",
  "Glass & Side & Top",
  "Glass & Side",
  "Glass",
  // BOPP (labels / stickers)
  "Clear BOPP",
  "White BOPP",
  "Silver BOPP",
  "Holo BOPP",
  // Label Sheets
  "Gloss Label Sheet",
  "Matte Label Sheet",
  "Semi Gloss",
  // Cardstock (16th Street)
  "14pt C1S",
  "14pt C2S",
  "16pt C1S",
  "16pt C2S",
  "18pt C1S",
  "18pt C2S",
  "18pt Silver",
  "24pt C1S",
  "24pt C2S",
  // Cardstock / Sheet (Boyd Street)
  "16pt (Boyd)",
  "18pt (Boyd)",
  "20pt (Boyd)",
  "24pt (Boyd)",
  // Cover / Text
  "80lb Cover",
  "100lb Cover",
  "110lb Cover",
  "80lb Text",
  "100lb Text",
  // Vinyl (Boyd Street)
  "White Vinyl",
  "White Vinyl - Aggressive Glue",
  "Holographic Vinyl",
  // Specialty / Large Format
  "Banner Material",
  "Window Decal",
  "Self-Adhesive (Peel-and-Stick)",
  "Traditional / Unpasted",
  // Apparel
  "Sweatshirt",
  "Hoodie",
  "Polo",
  "Tee",
  "Activewear",
  "Hat",
  "Bikini",
  "Short",
  "Jogger",
] as const;

/** Valid materials per product — for future cascading dropdown logic. */
export const PRODUCT_MATERIALS: Record<string, string[]> = {
  "Pouches Combo": ["Pouch Double sided", "Pouche One sided"],
  "Jar Combo": [
    "Plastic & Side & Top",
    "Glass & Side & Top",
    "Glass & Side",
    "Plastic & Top",
    "Glass",
  ],
  "Tube Combo": [
    "Plastic & Side",
    "Plastic & Side & Top",
    "Glass & Side & Top",
    "Glass & Side",
    "Plastic & Top",
    "Glass",
  ],
  "Labels (Roll)": [
    "Clear BOPP",
    "White BOPP",
    "Silver BOPP",
    "Holo BOPP",
    "Gloss Label Sheet",
    "Matte Label Sheet",
    "Semi Gloss",
  ],
  "Labels (Sheet)": [
    "Gloss Label Sheet",
    "Matte Label Sheet",
    "Semi Gloss",
  ],
  "Folding Cartons / Boxes": [
    "14pt C1S",
    "14pt C2S",
    "16pt C1S",
    "16pt C2S",
    "18pt C1S",
    "18pt C2S",
    "18pt Silver",
    "24pt C1S",
    "24pt C2S",
    "16pt (Boyd)",
    "18pt (Boyd)",
    "20pt (Boyd)",
    "24pt (Boyd)",
  ],
  "Business Cards": [
    "14pt C1S",
    "14pt C2S",
    "16pt C1S",
    "16pt C2S",
    "18pt C1S",
    "18pt C2S",
    "18pt Silver",
    "24pt C1S",
    "24pt C2S",
    "80lb Cover",
    "100lb Cover",
    "110lb Cover",
  ],
  "Flyers / Postcards": [
    "14pt C1S",
    "14pt C2S",
    "16pt C1S",
    "16pt C2S",
    "18pt C1S",
    "18pt C2S",
    "18pt Silver",
    "24pt C1S",
    "24pt C2S",
    "80lb Cover",
    "100lb Cover",
    "110lb Cover",
    "80lb Text",
    "100lb Text",
  ],
  Booklets: [
    "80lb Cover",
    "100lb Cover",
    "110lb Cover",
    "80lb Text",
    "100lb Text",
  ],
  "Diecut Stickers": [
    "Clear BOPP",
    "White BOPP",
    "Silver BOPP",
    "Holo BOPP",
    "Gloss Label Sheet",
    "Matte Label Sheet",
    "Semi Gloss",
    "White Vinyl",
    "White Vinyl - Aggressive Glue",
    "Holographic Vinyl",
  ],
  "Vinyl Labels / 54'' Rolls": [
    "White Vinyl",
    "White Vinyl - Aggressive Glue",
    "Holographic Vinyl",
  ],
  "Vinyl Signage": [
    "White Vinyl",
    "White Vinyl - Aggressive Glue",
    "Holographic Vinyl",
  ],
  "Banners / Large Format": [
    "Banner Material",
    "Window Decal",
    "Self-Adhesive (Peel-and-Stick)",
    "Traditional / Unpasted",
  ],
  "Window Decals": ["Window Decal"],
  Wallpaper: ["Self-Adhesive (Peel-and-Stick)", "Traditional / Unpasted"],
  "Sheet Products (Boyd)": ["18pt (Boyd)", "20pt (Boyd)", "24pt (Boyd)"],
  Apparel: [
    "Sweatshirt",
    "Hoodie",
    "Polo",
    "Tee",
    "Activewear",
    "Hat",
    "Bikini",
    "Short",
    "Jogger",
  ],
  "Pouches Only": [
    "Clear Cosmetic Web",
    "White Cosmetic Web",
    "Silver Cosmetic Web",
  ],
  "Tube Only": ["Plastic", "Glass"],
  "Jar Only": ["Plastic", "Glass"],
  Other: [],
};
